# Generated by Django 5.2.7 on 2025-10-29 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("dateofsign", models.DateField(default=django.utils.timezone.now)),
                ("fathername", models.CharField(blank=True, max_length=100, null=True)),
                ("mothername", models.CharField(blank=True, max_length=100, null=True)),
                ("standard", models.CharField(blank=True, max_length=2, null=True)),
                ("phonenumber", models.CharField(blank=True, max_length=16, null=True)),
                ("email", models.EmailField(max_length=191, unique=True)),
                ("schoolname", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
