# Generated by Django 5.2.7 on 2025-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="password",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
