# Generated by Django 5.2.7 on 2025-11-10 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0002_signup_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="fileStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Filename", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("filepath", models.FileField(upload_to="uploads/")),
                (
                    "studentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Myapp.signup"
                    ),
                ),
            ],
        ),
    ]
