# Generated by Django 5.2.7 on 2025-11-11 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0003_filestore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "studentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Myapp.signup"
                    ),
                ),
            ],
        ),
    ]
