# Generated by Django 5.2.7 on 2025-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0004_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="replay",
            field=models.TextField(blank=True),
        ),
    ]
